commit 2 new
ez4vad/hw-figma pull request #3
Opened 2024-06-17 15:45 UTC by ez4vad

2024-06-20 15:21 UTC, a1exalexander commented
PR в драфті, якщо шо
https://github.blog/2019-02-14-introducing-draft-pull-requests/
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request

2024-06-24 09:16 UTC, a1exalexander requested changes

2024-06-24 09:16 UTC, a1exalexander commented on index.html
> +    </nav>
тег `nav` суто для навігації, тобто в середині нього мають бути посилання але можна додавати й інші елементи, якщо вони пов'язані з цією навігацією
```suggestion
    <div>
        <a href="/">
            <img src="Logo.svg" alt="">
        </a>
        <nav>
            <a href="#product">Product</a>
            <a href="#product">Customers</a>
            <a href="#product">Pricing</a>
            <a href="#product">Resources</a>
        </nav>
        <button><img src="Button1.svg" alt=""></button>
        <button><img src="Button2.svg" alt=""></button>
    </div>
```

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav
https://www.w3schools.com/tags/tag_nav.asp

2024-06-24 09:16 UTC, a1exalexander commented on index.html
> +        <img src="1.svg" alt="">
це список

2024-06-24 09:16 UTC, a1exalexander commented on index.html
> +            FAQ</p>
це списки з посиланнями
ul > li > a

2024-06-25 20:27 UTC, ez4vad reviewed
исправил

2024-09-06 20:18 UTC, merged